services:
    filebrowser:
        image: filebrowser/filebrowser:latest
        container_name: filebrowser
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - "8080:80"
        volumes:
            - ./volumes/data:/srv
            - ./volumes/filebrowser.db:/database/filebrowser.db
            - ./volumes/settings.json:/config/settings.json
